module.exports = {
  PROJECT_STATUS: {
    IN_DEVELOPMENT: "IN_DEVELOPMENT",
    ON_HOLD: "ON_HOLD",
    COMPLETED: "COMPLETED",
  },
  TASK: {
    STATUS: {
      OPEN: "OPEN",
      TO_DO: "TO_DO",
      IN_PROGRESS: "IN_PROGRESS",
      IN_REVIEW: "IN_REVIEW",
      REWORK: "REWORK",
      COMPLETED: "COMPLETED",
    },
    PRIORITY: {
      LOW: "LOW",
      MEDIUM: "MEDIUM",
      HIGH: "HIGH",
      HIGHEST: "HIGHEST",
    },
  },
  META_CODE: {
    SUCCESS: 1,
    FAIL: 0,
  },
  RESPONSE_CODE: {
    SUCCESS: 200,
    SUCCESS_NEW_RESOURCE: 201,
    SUCCESS_WITHOUT_RESPONSE: 204,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    NOT_FOUND: 404,
    FORBIDDEN: 403,
    UPGRADE_REQUIRED: 426,
    INTERNAL_SERVER: 500,
    MAINTENANCE: 503,
    TOKEN_INAVLID: 498,
  },
};
